name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: queryboi*()00
      DATABASE_NAME: fastapi_db
      DATABASE_USERNAME: postgres
      SECRET_KEY: c7aaacc8a5a0877157e2c050bb232f7416a516e4f51045d0cba896f1653cedd1
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: Install python version 3.11.3
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.3"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest